### PR TITLE
raid1_rh.sh: Make md RAID creation fail proof (fixes #40)

### LINKED ISSUE #40: raid1_rh.sh may fail if a previous md raid exists
Hi,

this is just for reference and you may want to add a few changes I did to radi1_rh.sh.

For me raid1_rh.sh failed if a previous md raid with a different layout existed.

I got the following error:
```
[2018-09-20T02:40:11+02:00] An unknown error has occured, look at the /tmp/anaconda-tb* file(s) for more details
[2018-09-20T02:40:11+02:00] ESC[1;24rESC[HESC[23;1HESC[1;23rESC[HESC[23;1H
[2018-09-20T02:40:14+02:00] ===============================================================================
[2018-09-20T02:40:14+02:00] An unknown error has occurred
[2018-09-20T02:40:14+02:00] ===============================================================================
[2018-09-20T02:40:14+02:00] anaconda 21.48.22.134-1 exception report
[2018-09-20T02:40:14+02:00] Traceback (most recent call first):
[2018-09-20T02:40:14+02:00]   File "/usr/lib/python2.7/site-packages/blivet/devicelibs/mdraid.py", line 253, in mddeactivate
[2018-09-20T02:40:14+02:00]     raise MDRaidError("mddeactivate failed for %s: %s" % (device, msg))
[2018-09-20T02:40:14+02:00]   File "/usr/lib/python2.7/site-packages/blivet/devices/md.py", line 548, in teardown
[2018-09-20T02:40:14+02:00]     mdraid.mddeactivate(self.path)
[2018-09-20T02:40:14+02:00]   File "/usr/lib/python2.7/site-packages/blivet/devices/storage.py", line 515, in _preDestroy
[2018-09-20T02:40:14+02:00]     self.teardown()
[2018-09-20T02:40:14+02:00]   File "/usr/lib/python2.7/site-packages/blivet/devices/storage.py", line 524, in destroy
[2018-09-20T02:40:14+02:00]     self._preDestroy()
[2018-09-20T02:40:14+02:00]   File "/usr/lib/python2.7/site-packages/blivet/deviceaction.py", line 344, in execute
[2018-09-20T02:40:14+02:00]     self.device.destroy()
[2018-09-20T02:40:14+02:00]   File "/usr/lib/python2.7/site-packages/blivet/devicetree.py", line 373, in processActions
[2018-09-20T02:40:14+02:00]     action.execute(callbacks)
[2018-09-20T02:40:14+02:00]   File "/usr/lib/python2.7/site-packages/blivet/__init__.py", line 380, in doIt
[2018-09-20T02:40:14+02:00]     self.devicetree.processActions(callbacks)
[2018-09-20T02:40:14+02:00]   File "/usr/lib/python2.7/site-packages/blivet/__init__.py", line 230, in turnOnFilesystems
[2018-09-20T02:40:14+02:00]     storage.doIt(callbacks)
[2018-09-20T02:40:14+02:00]   File "/usr/lib64/python2.7/site-packages/pyanaconda/install.py", line 206, in doInstall
[2018-09-20T02:40:14+02:00]     turnOnFilesystems(storage, mountOnly=flags.flags.dirInstall, callbacks=callbacks_reg)
[2018-09-20T02:40:14+02:00]   File "/usr/lib64/python2.7/threading.py", line 765, in run
[2018-09-20T02:40:14+02:00]     self.__target(*self.__args, **self.__kwargs)
[2018-09-20T02:40:14+02:00]   File "/usr/lib64/python2.7/site-packages/pyanaconda/threads.py", line 227, in run
[2018-09-20T02:40:14+02:00]     threading.Thread.run(self, *args, **kwargs)
[2018-09-20T02:40:14+02:00] MDRaidError: mddeactivate failed for /dev/md/taurusml2:2: 1
[2018-09-20T02:40:14+02:00] 
[2018-09-20T02:40:14+02:00] What do you want to do now?
[2018-09-20T02:40:14+02:00] 1) Report Bug
[2018-09-20T02:40:14+02:00] 2) Debug
[2018-09-20T02:40:14+02:00] 3) Quit
```

I was able to fix this reliable by adding the following commands before part 2 in https://github.com/xcat2/xcat-extensions/blob/master/partition/raid1_rh.sh
```
# erase all existing md RAIDs
mdadm --stop /dev/md/*
mdadm --zero-superblock ${disk1}*
mdadm --zero-superblock ${disk2}*
```

Furthermore, I added the following as well:
```
# disable md RAID resync during installation
# this speeds up the installation process significantly
echo 0 > /proc/sys/dev/raid/speed_limit_max
echo 0 > /proc/sys/dev/raid/speed_limit_min
```
With these lines the installation process is way faster. Especially useful if you don't have SSDs.

### PR DESCRIPTION
**Pull request by Obihoernchen**
- Make sure previous md RAIDs are deleted c84d0327c4c5d18bb7e1a4cba1c2cca482a0e90b
- Disable md RAID resync during installation a074747deaac847fe424b7a6f63af551d3f068e3

See #40 for more information.

### CODE REVIEW

File: partition/raid1_rh.sh [hunk 1]
```diff
@@ -106,6 +106,15 @@ rm -fr $tmpdir
...
 disk2=$(tail -n +2 /tmp/xcat_sorted_disks|head -n1 |cut -d'|' -f 2|cut -d' ' -f1)
 
+# disable md RAID resync during installation
+# this speeds up the installation process significantly
+echo 0 > /proc/sys/dev/raid/speed_limit_max
+echo 0 > /proc/sys/dev/raid/speed_limit_min
+
+# erase all existing md RAIDs
+mdadm --stop /dev/md/*
+mdadm --zero-superblock ${disk1}*
```
Comment (neo954) [inline partition/raid1_rh.sh]: Say, the `${disk1}` would be `/dev/sda`. In a system with more than 26 disks, `/dev/sdaa` will exist. Beyond `/dev/sdzz`, there will be `/dev/sdaaa`.

Thus, use `*` here is not a good solution.

File: partition/raid1_rh.sh [hunk 2]
```diff
@@ -106,6 +106,15 @@ rm -fr $tmpdir
 disk1=$(tail -n +1 /tmp/xcat_sorted_disks|head -n1 |cut -d'|' -f 2|cut -d' ' -f1)
 disk2=$(tail -n +2 /tmp/xcat_sorted_disks|head -n1 |cut -d'|' -f 2|cut -d' ' -f1)
 
+# disable md RAID resync during installation
+# this speeds up the installation process significantly
+echo 0 > /proc/sys/dev/raid/speed_limit_max
+echo 0 > /proc/sys/dev/raid/speed_limit_min
+
+# erase all existing md RAIDs
+mdadm --stop /dev/md/*
```
Comment (neo954) [inline partition/raid1_rh.sh]: This may affect disks other than the disk going to be installed. Like data disks intend to be preserved during operating system reinstallation.

Maybe, it is better to check `/proc/mdstat` and stop the affected md devices only.

**Review by neo954 — CHANGES_REQUESTED** [review]

File: partition/raid1_rh.sh (hunk 1 above)
Comment (Obihoernchen) [reply partition/raid1_rh.sh]: Good points! Will work on a fix.

**Comment by Obihoernchen** [comment]
Hey @neo954 please have a look at my latest commits (especially 0e415d6).

1. Search for disk1 (ex: sda) and disk2 (ex. sdb) in `/proc/mdstat` to find all md RAIDs on these disks
2. Stop all md RAIDs found in 1.
3. Finally, the superblock zeroing is done for all partitions on disk1 and disk2 only

Works like this (I've just added an echo for each mdadm command for the output):
```
[rh75-compute-install.partition] get a disk: sdb
[rh75-compute-install.partition] get a disk: sda
[rh75-compute-install.partition] disk sdb has wwn:0x5000c500aadde735
[rh75-compute-install.partition] disk sda has wwn:0x5000c500a8f628fc
[rh75-compute-install.partition] get disk: (sda sdb) with sort_type:wwn
[rh75-compute-install.partition] the final disk order:
[rh75-compute-install.partition]       sda | /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W4708JNJ /dev/disk/by-id/wwn-0x5000c500a8f628fc /dev/disk/by-path/pci-0004:03:00.0-ata-1.0
[rh75-compute-install.partition]       sdb | /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W470V7KY /dev/disk/by-id/wwn-0x5000c500aadde735 /dev/disk/by-path/pci-0004:03:00.0-ata-2.0
[rh75-compute-install.partition] the output file is: /tmp/xcat_sorted_disks
[rh75-compute-install.partition] disabling md RAID resync during installation
[rh75-compute-install.partition] stopping md device: /dev/md/0
mdadm --stop /dev/md/0
[rh75-compute-install.partition] stopping md device: /dev/md/1
mdadm --stop /dev/md/1
[rh75-compute-install.partition] stopping md device: /dev/md/2
mdadm --stop /dev/md/2
[rh75-compute-install.partition] stopping md device: /dev/md/3
mdadm --stop /dev/md/3
[rh75-compute-install.partition] stopping md device: /dev/md/4
mdadm --stop /dev/md/4
[rh75-compute-install.partition] zeroing superblocks of /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W4708JNJ-part*
mdadm --zero-superblock /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W4708JNJ-part1 /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W4708JNJ-part2 /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W4708JNJ-part3 /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W4708JNJ-part4 /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W4708JNJ-part5 /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W4708JNJ-part6 /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W4708JNJ-part7
[rh75-compute-install.partition] zeroing superblocks of /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W470V7KY-part*
mdadm --zero-superblock /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W470V7KY-part1 /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W470V7KY-part2 /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W470V7KY-part3 /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W470V7KY-part4 /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W470V7KY-part5 /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W470V7KY-part6 /dev/disk/by-id/ata-ST1000NX0313_00LY266_00LY265IBM_W470V7KY-part7
```

**Review by neo954 — CHANGES_REQUESTED** [review]
@Obihoernchen,

It is still not a common solution. In your patch, only two disks are checked, why? Maybe, there are only two disks in your machine. But as a product in common use, xCAT can not do this. There are machines have more than two disks. There are machines in different RAID configurations. xCAT needs provide a common solution.

Maybe, change the code to check `/proc/partitions`, and check all the disks.

**Comment by immarvin** [comment]
hi @neo954 , thanks for your comment, this partition script is just an example/template for admin to create a raid-1 setup on 2 disks, which is far from a common solution for raid setup, maybe we can put some effort to enhance it in the future, but this PR is adequate to for the issue to fix. 

After discuss with @neo954 , we would like to merge this, thanks for your contribution @Obihoernchen

**Comment by Obihoernchen** [comment]
Yes this script is basically only useful for stateful compute nodes or basic service nodes. Raid 5, Raid 10 etc. need some more attention ;)

**Comment by Obihoernchen** [comment]
`/proc/mdstat` is not fully populated during script execution :/
Therefore, this still fails if there is an incomplete md setup existing on the disk.

Unfortunately, checking `/proc/mdstat` does not work.
